/* Whenever you add a substantial amount of code from an external source
   (be it a full-blown framework or a GitHub gist), add it here.
   Use the format X(LIBRARY by AUTHOR [PSEUDONYM]), where:
     LIBRARY is the name of the code module (framework/library/class/etc.),
     AUTHOR is the author's full name (if unavailable, use their pseudonym),
     PSEUDONYM is the author's pseudonym where their code is published.
   As an exception, if it has many tens or hundreds of contributors
   (i.e., LLVM-scale), just write the library name.
 */
X(LLVM)
X(LLVMSwift by Harlan Haskins [harlanhaskins] & Robert Widmann [CodaFi])
X(SwiftAutomation.framework by Hamish Sanderson [hhas])
X(PreferencesViewController by Matthew Miner [mminer]) /* TODO: Should be in the Editor about box */
