import Bushel

/// An error generated by the Bushel language runtime.
public struct RuntimeError: LocalizedError, Located {
    
    /// The error message as formatted during init.
    public let description: String
    
    /// The source location to which the error applies.
    public var location: SourceLocation
    
    public var errorDescription: String? {
        description
    }
    
}

/// An error thrown by evaluating `raise` in user code.
public struct RaisedObjectError: LocalizedError, Located {
    
    /// The object given to `raise`.
    public let error: RT_Object
    
    /// The source location of the `raise` expression.
    public var location: SourceLocation
    
    public var errorDescription: String? {
        "\(error)"
    }
    
}
