name: Package

on: [push]

jobs:
  package:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Switch to Xcode 12.4
      run: sudo xcode-select -s /Applications/Xcode_12.4.app/Contents/Developer
    - name: Package release
      run: |
        cd "$GITHUB_WORKSPACE"
        function get_project_version {
          xcodebuild -showBuildSettings -workspace Bushel.xcworkspace -scheme BushelScript\ Editor | grep MARKETING_VERSION | head -1 | tr -d '[:alpha:][:space:]_='
        }
        export VERSION="$(get_project_version)+git.$(git rev-parse --short HEAD)"
        export INSTALL_DIR=install
        ./build.sh
        product='BushelScript Editor.app'
        mv install/Applications/"$product" .
        tar -cvf "$product"
        echo "artifact=BushelScript.v${VERSION}" >> "$GITHUB_ENV"
    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.artifact }}
        path: ${{ github.workspace }}/BushelScript.tar
