name: CI (Test and Package)

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install LLVM
      run: brew install llvm
    - name: Test
      run: |
        cd $GITHUB_WORKSPACE
        ./test.sh
    - name: Package
      run: |
        cd $GITHUB_WORKSPACE
        ./make-pkg.sh
    - name: Upload package
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: BushelScript.pkg
        path: ${{ env.GITHUB_WORKSPACE }}/BushelScript.pkg
