name: CI (Test and Package)

on: [push]

jobs:
  test-and-package:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Switch to Xcode 12.4
      run: sudo xcode-select -s /Applications/Xcode_12.4.app/Contents/Developer
    - name: Test
      run: |
        cd "$GITHUB_WORKSPACE"
        ./test.sh
    - name: Package
      run: |
        cd "$GITHUB_WORKSPACE"
        function get_project_version {
          xcodebuild -showBuildSettings -workspace Bushel.xcworkspace -scheme BushelScript\ Editor | grep MARKETING_VERSION | head -1 | tr -d '[:alpha:][:space:]_='
        }
        export VERSION="$(get_project_version)+git.$(git rev-parse --short HEAD)"
        export INSTALL_DIR=install
        ./build.sh
        file_name="BushelScript.v${VERSION}.zip"
        zip "$file_name" install/Applications/BushelScript.app
        echo "artifact=$file_name" >> "$GITHUB_ENV"
    - name: Upload package
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: ${{ env.artifact }}
        path: ${{ github.workspace }}/install/Applications/BushelScript.app
