name: CI (Test and Package)

on: [push]

jobs:
  test-and-package:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install LLVM
      run: brew install llvm
    - name: Make pkg-config file for LLVM
      run: |
        cd "$GITHUB_WORKSPACE"
        . ./resolve-packages.sh
        cd "$PACKAGES_DIR/checkouts/LLVMSwift"
        PATH="$(brew --prefix llvm)/bin:$PATH" swift utils/make-pkgconfig.swift
    - name: Test
      run: |
        cd "$GITHUB_WORKSPACE"
        ./test.sh
    - name: Package
      run: |
        cd "$GITHUB_WORKSPACE"
        ./make-pkg.sh
    - name: Upload package
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: BushelScript.pkg
        path: ${{ github.workspace }}/BushelScript.pkg
